### ISSUE TITLE
Oauth token

### ISSUE THREAD

**Issue by d1snin** [hanshsieh/pixivj#41]
I understand that I need to use some access token, so where can I get it? I searched on google and did not find any useful information on this, it would be nice if you could tell me how I can get this

**Comment by d1snin** [comment]
@hanshsieh :)

**Comment by hanshsieh** [comment]
You can use the plugin module I built: https://github.com/hanshsieh/pixivj-jfx
It uses JavaFX to open a web view to ask the user to login. Checkout the README for details.
You can also reference the integration test repo https://github.com/hanshsieh/pixivj-int, which contains workable examples.

**Comment by d1snin** [comment]
thank uu!!
